//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at http://docs.kentico.com.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine.Types.MedioClinic;
using CMS.DocumentEngine;

[assembly: RegisterDocumentType(Sociallinksfolder.CLASS_NAME, typeof(Sociallinksfolder))]

namespace CMS.DocumentEngine.Types.MedioClinic
{
	/// <summary>
	/// Represents a content item of type Sociallinksfolder.
	/// </summary>
	public partial class Sociallinksfolder : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "MedioClinic.Sociallinksfolder";


		/// <summary>
		/// The instance of the class that provides extended API for working with Sociallinksfolder fields.
		/// </summary>
		private readonly SociallinksfolderFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// SociallinksfolderID.
		/// </summary>
		[DatabaseIDField]
		public int SociallinksfolderID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("SociallinksfolderID"), 0);
			}
			set
			{
				SetValue("SociallinksfolderID", value);
			}
		}


		/// <summary>
		/// Folder Name.
		/// </summary>
		[DatabaseField]
		public string FolderName
		{
			get
			{
				return ValidationHelper.GetString(GetValue("FolderName"), @"");
			}
			set
			{
				SetValue("FolderName", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with Sociallinksfolder fields.
		/// </summary>
		[RegisterProperty]
		public SociallinksfolderFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with Sociallinksfolder fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class SociallinksfolderFields : AbstractHierarchicalObject<SociallinksfolderFields>
		{
			/// <summary>
			/// The content item of type Sociallinksfolder that is a target of the extended API.
			/// </summary>
			private readonly Sociallinksfolder mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="SociallinksfolderFields" /> class with the specified content item of type Sociallinksfolder.
			/// </summary>
			/// <param name="instance">The content item of type Sociallinksfolder that is a target of the extended API.</param>
			public SociallinksfolderFields(Sociallinksfolder instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// SociallinksfolderID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.SociallinksfolderID;
				}
				set
				{
					mInstance.SociallinksfolderID = value;
				}
			}


			/// <summary>
			/// Folder Name.
			/// </summary>
			public string FolderName
			{
				get
				{
					return mInstance.FolderName;
				}
				set
				{
					mInstance.FolderName = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="Sociallinksfolder" /> class.
		/// </summary>
		public Sociallinksfolder() : base(CLASS_NAME)
		{
			mFields = new SociallinksfolderFields(this);
		}

		#endregion
	}
}